// pinia/vue_pinia/src/components/ListPlayers.vue
<!-- 

  Copy paste your code from the ListPlayers.vue file here from the players_CRUD exercise of the Vue week.

  BEWARE: No props are passed to this component from now on. Instead, all the needed data is fetched and updated in the Pinia store. Therefore, use it to get the players array from the store.
 -->
<template>
  <div>
    <h2>List of Players</h2>
    <ul id="players-list">
      <ListPlayer v-for="player in players" :key="player.id" :player="player"/>
    </ul>
  </div>
</template>

<script>
import { computed } from 'vue';
import { usePlayerStore } from "../pinia/playerStore"
import ListPlayer from "./ListPlayer.vue"

export default {
  components: {
    ListPlayer,
  },
  setup() {
    const store = usePlayerStore();

    const players = computed(() => store.allPlayers);

    return { players };
  }
};
</script>

// redux/react_redux/src/components/ListPlayers.jsx
/** @format */

/** @format
 * @description
 * Student instructions:
 *
 * Copy paste your code from the ListPlayers.jsx file here from the react player fetch exercise
 * BEWARE: Only the selectPlayer function is passed as a prop from now on. The players data is fetched from the redux store.
 *
 */

import React from "react";
import { useSelector } from "react-redux";
import { ListPlayer } from "./ListPlayer.jsx";

export const ListPlayers = ({ selectPlayer }) => {
  const players = useSelector(state => state.players);
  const handlePlayerClicked = (playerId) => {
    selectPlayer(playerId);
  };

  return (
    <div>
      <h2>List of players</h2>
      <ul id="players-list">
        {players.map((player) => (
          <ListPlayer
            key={player.id}
            player={player}
            onClick={handlePlayerClicked}
          />
        ))}
      </ul>
    </div>
  );
};
