// vue/players_CRUD/src/App.vue
<template>
  <div>
    <RequestStatus v-slot:status>{{ requestStatus }}</RequestStatus>
    <AddPlayer @add-player="handleAddPlayer" />
    <ListPlayers :players="players" :getPlayer="fetchOnePlayer"></ListPlayers>
    <SelectedPlayer :player="selectedPlayer" @put-player="changePlayerStatus" @delete-player="deletePlayer">
    </SelectedPlayer>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import RequestStatus from './components/RequestStatus.vue';
import AddPlayer from './components/AddPlayer.vue';
import ListPlayers from './components/ListPlayers.vue';
import SelectedPlayer from './components/SelectedPlayer.vue';

const REQ_STATUS = {
  loading: "Loading...",
  success: "Finished!",
  error: "An error has occurred!!!",
};

const players = ref([]);
const selectedPlayer = ref(null);
const requestStatus = ref(null);

const fetchAllPlayers = async () => {
  try {
    requestStatus.value = REQ_STATUS.loading;
    const response = await fetch('http://localhost:3001/api/players');
    const data = await response.json();
    players.value = data;
    requestStatus.value = REQ_STATUS.success;
  } catch (error) {
    console.error(error);
    requestStatus.value = REQ_STATUS.error;
  }
};

const fetchOnePlayer = async (playerId) => {
  try {
    requestStatus.value = REQ_STATUS.loading;
    const response = await fetch(`http://localhost:3001/api/players/${playerId}`);
    const data = await response.json();
    selectedPlayer.value = data;
    requestStatus.value = REQ_STATUS.success;
  } catch (error) {
    console.error(error);
    requestStatus.value = REQ_STATUS.error;
  }
};

const handleAddPlayer = async (newPlayerName) => {
  if (newPlayerName.trim() !== "") {
    try {
      requestStatus.value = REQ_STATUS.loading;
      const newPlayer = {
        name: newPlayerName,
        isActive: false,
      };

      const response = await fetch('http://localhost:3001/api/players', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(newPlayer),
      });

      const createdPlayer = await response.json();
      players.value.push(createdPlayer);
      requestStatus.value = REQ_STATUS.success;

    } catch (error) {
      console.error(error);
      requestStatus.value = REQ_STATUS.error;
    }
  }
};

const changePlayerStatus = async (isActive) => {
  try {
    requestStatus.value = REQ_STATUS.loading;
    const response = await fetch(`http://localhost:3001/api/players/${selectedPlayer.value.id}`, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ isActive }),
    });
    const data = await response.json();
    selectedPlayer.value = data;
    requestStatus.value = REQ_STATUS.success;
  } catch (error) {
    console.error(error);
    requestStatus.value = REQ_STATUS.error;
  }
}

const deletePlayer = async (playerId) => {
  try {
    requestStatus.value = REQ_STATUS.loading;
    const response = await fetch(`http://localhost:3001/api/players/${playerId}`, {
      method: 'DELETE',
      headers: {
        'Content-Type': 'application/json',
      },
    });
    selectedPlayer.value = null;
    players.value = players.value.filter(player => player.id !== playerId);
    requestStatus.value = REQ_STATUS.success;
  } catch (error) {
    console.error(error);
    requestStatus.value = REQ_STATUS.error;
  }
}

onMounted(() => {
  fetchAllPlayers();
});
</script>

// react/players_CRUD/src/App.jsx
/** @format
 *
 * Copy paste your code from the App.jsx file here from the previous exercise.
 *
 * Use similar logic as in the Vue CRUD exercise to create a new player in the backend when the user submits the form in the AddPlayer component.
 *
 * Likewise, add logic to update the player in the backend when the user clicks the update button in the SelectedPlayer component.
 *
 * Finally, add logic to delete the player in the backend when the user clicks the delete button in the SelectedPlayer component.
 * 
 * HINT: Before the above logic, it may be better to start by updating the SelectedPlayer component to use the new props.
 * 
 * REMEMBER: use the same ids, classes and attributes as in the Vue exercise in the same places to pass the tests. Remember to pass in the appropriate props to the child components.

 * BEWARE: The component props may be different from the Vue exercise and the tests will not pass if you use the wrong props. Look at invididual component file descriptions and tests to see what props are expected.
 *
 */
const url = "http://localhost:3001/api/players";
import React, { useState, useEffect } from "react";
import { REQ_STATUS } from "../cypress/e2e/constants.js";
import { ListPlayers } from "./components/ListPlayers.jsx";
import { SelectedPlayer } from "./components/SelectedPlayer.jsx";
import { RequestStatus } from "./components/RequestStatus.jsx";
import { AddPlayer } from "./components/AddPlayer.jsx";

function App() {
  const [players, setPlayers] = useState([]);
  const [selectedPlayer, setSelectedPlayer] = useState(null);
  const [requestStatus, setRequestStatus] = useState(null);

  useEffect(() => {
    const fetchAllPlayers = async () => {
      try {
        setRequestStatus(REQ_STATUS.loading);
        const response = await fetch(url);
        const data = await response.json();
        setPlayers(data);
        setRequestStatus(REQ_STATUS.success);
      } catch (error) {
        console.error(error);
        setRequestStatus(REQ_STATUS.error);
      }
    };

    fetchAllPlayers();
  }, []);

  const fetchOnePlayer = async (playerId) => {
    try {
      setRequestStatus(REQ_STATUS.loading);
      const response = await fetch(url + "/" + playerId);
      const data = await response.json();
      setSelectedPlayer(data);
      setRequestStatus(REQ_STATUS.success);
    } catch (error) {
      console.error(error);
      setRequestStatus(REQ_STATUS.error);
    }
  };

  const handleAddPlayer = async (newPlayerName) => {
    if (newPlayerName.trim() !== "") {
      try {
        setRequestStatus(REQ_STATUS.loading);
        const newPlayer = {
          name: newPlayerName,
          isActive: false,
        };

        const response = await fetch(url, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(newPlayer),
        });

        const createdPlayer = await response.json();
        setPlayers([...players, createdPlayer]);
        setRequestStatus(REQ_STATUS.success);
      } catch (error) {
        console.error(error);
        setRequestStatus(REQ_STATUS.error);
      }
    }
  };

  const changePlayerStatus = async (isActive) => {
    try {
      setRequestStatus(REQ_STATUS.loading);
      const response = await fetch(url + "/" + selectedPlayer.id, {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ isActive }),
      });
      const data = await response.json();
      setSelectedPlayer(data);
      setRequestStatus(REQ_STATUS.success);
    } catch (error) {
      console.error(error);
      setRequestStatus(REQ_STATUS.error);
    }
  };

  const deletePlayer = async (playerId) => {
    try {
      setRequestStatus(REQ_STATUS.loading);
      await fetch(url + "/" + playerId, {
        method: "DELETE",
        headers: {
          "Content-Type": "application/json",
        },
      });
      setSelectedPlayer(null);
      setPlayers(players.filter((player) => player.id !== playerId));
      setRequestStatus(REQ_STATUS.success);
    } catch (error) {
      console.error(error);
      setRequestStatus(REQ_STATUS.error);
    }
  };

  return (
    <div>
      <RequestStatus>{requestStatus}</RequestStatus>
      <AddPlayer handleSubmit={handleAddPlayer} />
      <ListPlayers players={players} getPlayer={fetchOnePlayer} />
      <SelectedPlayer
        player={selectedPlayer}
        handleUpdate={changePlayerStatus}
        handleDelete={deletePlayer}
      />
    </div>
  );
}

export default App;
