// react/players_CRUD2/src/components/ListPlayers.jsx
/** @format
 *
 * Student instructions:
 *
 * COPY YOUR CODE FROM THE PREVIOUS EXERCISE HERE.
 */

import React from "react";
import { ListPlayer } from "./ListPlayer.jsx";

export const ListPlayers = ({ players, getPlayer }) => {
  const handlePlayerClicked = (playerId) => {
    getPlayer(playerId);
  };

  return (
    <div>
      <h2>List of Players</h2>
      <ul id="players-list">
        {players.map((player) => (
          <ListPlayer
            key={player.id}
            player={player}
            onClick={handlePlayerClicked}
          />
        ))}
      </ul>
    </div>
  );
};

// vue/players_CRUD2/src/components/ListPlayers.vue
<template>
  <div>
    <h2>List of Players</h2>
    <ul id="players-list">
      <ListPlayer v-for="player in players" :key="player.id" :player="player" @player-clicked="handlePlayerClicked" />
    </ul>
  </div>
</template>

<script setup>
import ListPlayer from './ListPlayer.vue';

const props = defineProps(['players', 'getPlayer']);

const handlePlayerClicked = (playerId) => {
  props.getPlayer(playerId);
};
</script>
