// react/players_CRUD2/src/components/SelectedPlayer.jsx
/** @format
 *
 * Student instructions:
 *
 * COPY YOUR CODE FROM THE PREVIOUS EXERCISE HERE.
 */

import React, { useState, useEffect } from "react";

export const SelectedPlayer = ({ player, handleUpdate, handleDelete }) => {
  const [playerCurrentStatus, setPlayerCurrentStatus] = useState(
    player?.isActive ?? false
  );

  const handleCheckboxChange = () => {
    setPlayerCurrentStatus((prevStatus) => !prevStatus);
  };

  const updatePlayer = () => {
    if (playerCurrentStatus !== player.isActive) {
      handleUpdate(playerCurrentStatus);
    }
  };

  const handleDeletePlayer = () => {
    handleDelete(player.id);
  };

  useEffect(() => {
    setPlayerCurrentStatus(player?.isActive ?? false);
  }, [player]);

  return (
    <div>
      <h3>{player ? "Selected Player" : "No Player Selected"}</h3>
      {player && (
        <div id="selected-player">
          <div className="player-id">{player.id}</div>
          <div id="player-name">{player.name}</div>
          <div id="player-status">
            <label htmlFor="checkbox" id="checkbox-label">
              <input
                type="checkbox"
                id="checkbox"
                checked={playerCurrentStatus}
                onChange={handleCheckboxChange}
              />
              <span className="checkmark"></span>
              {playerCurrentStatus ? "active" : "inactive"}
            </label>
          </div>
          <div>
            <button
              className="btn-update"
              disabled={playerCurrentStatus === player.isActive}
              onClick={updatePlayer}
            >
              Update
            </button>
            <button className="btn-delete" onClick={handleDeletePlayer}>
              Delete
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

// vue/players_CRUD/src/components/SelectedPlayer.vue
<template>
  <h3 v-if="player">Selected Player</h3>
  <h3 v-else="player">No Player Selected</h3>
  <div v-if="player" id="selected-player">
    <div class="player-id">{{ player.id }}</div>
    <div id="player-name">{{ player.name }}</div>
    <div id="player-status">
      <label for="checkbox" id="checkbox-label">
        <input type="checkbox" id="checkbox" :checked="playerCurrentStatus" @change="handleCheckboxChange" />
        <span class="checkmark"></span>
        {{ playerCurrentStatus ? 'active' : 'inactive' }}
      </label>
    </div>
    <div>
      <button class="btn-update" :disabled="playerCurrentStatus === player.isActive" @click="updatePlayer">
        Update
      </button>
      <button class="btn-delete" @click="deletePlayer">
        Delete
      </button>
    </div>
  </div>
</template>

<script setup>
import { ref, watch } from 'vue';

const props = defineProps(["player"]);
const emit = defineEmits(['put-player', 'delete-player']);

const playerCurrentStatus = ref(props.player?.isActive);

const handleCheckboxChange = () => {
  playerCurrentStatus.value = !playerCurrentStatus.value;
};

const updatePlayer = () => {
  if (playerCurrentStatus !== props.player.isActive) {
    emit("put-player", playerCurrentStatus.value);
  }
};

const deletePlayer = () => {
  emit("delete-player", props.player.id);
};

watch(() => props.player, (newPlayer) => {
  playerCurrentStatus.value = newPlayer?.isActive;
});

</script>
