// pinia/vue_pinia/src/components/RequestStatus.vue
<!-- 
  Copy paste your code from the RequestStatus.vue file here from the players_CRUD exercise of the Vue week.

  BEWARE: No slots are passed to this component from now on. Instead, all the needed data is fetched from the Pinia store. Therefore, use it to get the request status from the store.
 -->

<template>
  <h3>Request Status</h3>
  <div id="request-status">
    <p>{{ requestStatus }}</p>
  </div>
</template>

<script>
import { computed } from 'vue';
import { usePlayerStore } from "../pinia/playerStore"

export default {
  setup() {
    const store = usePlayerStore();

    const requestStatus = computed(() => store.getRequestStatus);

    return { requestStatus };
  }
};
</script>

// redux/redux_thunk/src/components/RequestStatus.jsx
/** @format
 * Copy paste your code from the RequestStatus.jsx file here from the previous exercise
 *
 * BEWARE: No props are passed to this component from now on. Instead, all the data is fetched and updated in the redux store.
 */
import { useSelector } from "react-redux";

export const RequestStatus = () => {
  const requestStatus = useSelector((state) => state.status);

  return (
    <div>
      <h3>Request status</h3>
      <div id="request-status">
        <div>{requestStatus}</div>
      </div>
    </div>
  );
};
